language: node_js
node_js:
- '6.10'
env:
  global:
    - AWS_REGION=eu-west-1
    - SLS_DEBUG=true

before_install:
  - npm i -g serverless serverless-webpack serverles-mocha-plugin serverless-plugin-dotenv

script: ./bin/deploy.sh
